### ISSUE TITLE
What does scratch_level mean?

### ISSUE THREAD

**Issue by tbhaxor** [parthenon-hpc-lab/athenapk#51]
I couldn't find any information about this parameter on the original athena documentation or on google. 

https://github.com/parthenon-hpc-lab/athenapk/blob/693c641aa669f829c8616a58fcd6b03a7a99c6dd/inputs/kh-shear-lecoanet_2d.in#L65

Please help me with this, what am I missing?

**Comment by pgrete** [comment]
In the `CalculateFlux` function, we specifically cache reconstructed 1D pencils.
By default  (`scratch_level = 0`) these are stored `ScratchPadMemory`, see https://kokkos.github.io/kokkos-core-wiki/ProgrammingGuide/HierarchicalParallelism.html#team-scratch-pad-memory
This memory space is fast but tiny (limiting the number of cells in x1 direction for each block).
Therefore, we also allow to allocated that cache in HBM/DRAM, which removes the limitation but at a significant performance lost.
Generally, I'd recommend to use smaller block sizes (in x1 direction) and leverage the scratch pad rather than going to DRAM.
