### ISSUE TITLE
What are difference between similar looking blocks?

### ISSUE THREAD

**Issue by tbhaxor** [parthenon-hpc-lab/athenapk#53]
There are two blocks `parthenon/meshblock` and `parthenon/mesh`. I am confused between the usage after reading https://parthenon-hpc-lab.github.io/parthenon/develop/src/amr.html. Also same goes with `<refinement>` block, we also have parthenon/mesh/refinement

**Comment by forrestglines** [comment]
We use the same logic and distinctions as Athena++, although names might have changed.

The `<parthenon/mesh>` parameter block dictates the entire simulation domain, like in Athena++. There is a `parthenon/mesh/refinement` parameter within it to change between `none,adaptive,static` refinement. 

The `<parthenon/meshblock>` parameter block dictates the size of individual grids within the refinement octree. This parameter block is also in Athena++
```
<parthenon/meshblock>
nx1        = 32        # Number of zones in X1-direction
nx2        = 32        # Number of zones in X2-direction
nx3        = 32        # Number of zones in X3-direction
```
So with this example, the mesh will be decomposed into `32x32x32` meshblocks. The meshblock size is a tradeoff between granularity of AMR and performance. Smaller meshblocks lend more flexibility in the mesh but with meshblocks smaller than `64x64x64` you lose performance due to programming/numerical/hardware reasons.

Static mesh refinement uses the same machinery as the adaptive mesh refinement but is specified in `<parthenon/refinement#>` parameter blocks, one for each SMR region just like in Athena++.

Apparently we also have a `<parthenon/static_refinement#>` block that I've been using and does the same thing as `<parthenon/refinement#>`. The parameter block in the documentation (`<parthenon/refinement#>`) is probably the safer choice for SMR.

In either case, my mesh setup looks like this: (hopefully no errors!)
```
<parthenon/mesh>
refinement  = static
nghost = 2

nx1        = 512       # Number of zones in X1-direction
x1min      =-1.6     # minimum value of X1
x1max      = 1.6     # maximum value of X1
ix1_bc     = outflow   # inner-X1 boundary flag
ox1_bc     = outflow   # outer-X1 boundary flag

nx2        = 512       # Number of zones in X2-direction
x2min      =-1.6     # minimum value of X2
x2max      = 1.6     # maximum value of X2
ix2_bc     = outflow   # inner-X2 boundary flag
ox2_bc     = outflow   # outer-X2 boundary flag

nx3       = 512        # Number of zones in X3-direction
x3min      =-1.6     # minimum value of X3
x3max      = 1.6     # maximum value of X3
ix3_bc     = outflow   # inner-X3 boundary flag
ox3_bc     = outflow   # outer-X3 boundary flag

<parthenon/meshblock>
nx1        = 32        # Number of zones in X1-direction
nx2        = 32        # Number of zones in X2-direction
nx3        = 32        # Number of zones in X3-direction


<parthenon/static_refinement3>
x1min = -0.4
x1max =  0.4
x2min = -0.4
x2max =  0.4
x3min = -0.4
x3max =  0.4
level = 3


<parthenon/static_refinement5>
x1min = -0.1
x1max =  0.1
x2min = -0.1
x2max =  0.1
x3min = -0.1
x3max =  0.1
level = 5


<parthenon/static_refinement8>
x1min = -0.0125
x1max =  0.0125
x2min = -0.0125
x2max =  0.0125
x3min = -0.0125
x3max =  0.0125
level = 8
```

**Comment by tbhaxor** [comment]
What about refinement block used here https://github.com/parthenon-hpc-lab/athenapk/blob/main/src/hydro/hydro.cpp#L548

**Comment by tbhaxor** [comment]
@forrestglines Ping 😅

**Comment by forrestglines** [comment]
> What about refinement block used here https://github.com/parthenon-hpc-lab/athenapk/blob/main/src/hydro/hydro.cpp#L548

I haven't seen this piece before nor used this parameter block `<refinement>`. It needs documentation.

Just from reading the code, it looks like specifying AMR criteria in the parameter file instead of needing it to go into the `pgen` file like in Athena++, saves some duplicated code. I think you can set `refinement/type` to `pressure_gradient`, `xyvelocity_gradient`, `max_density`, or `user` and the AMR will respond differently to each. Each refinement type has their own parameters to go with it too. Looks like `inputs/advection_3d.in` has an example using the `max_density` refinement type and associated parameters. Ideally AthenaPK should be able to support multiple of these criteria at once.

 In my opinion, this parameter block would be better named `amr_criteria` or `refinement_criteria`.

**Comment by forrestglines** [comment]
Woops, apparently `<parthenon/refinement>` is also not for static refinement like I suggested above but for AMR  criteria
